import { Render } from "./noact"

/*
 * - GENERATED CODE -
 *
 * This list can be scraped from https://developer.mozilla.org/en-US/docs/Web/HTML/Element

;(() => {
  const selector = `li.toggle:nth-child(7) > details:nth-child(1) > ol > li code` // Update me if needed
  const stringify = (e) => {
    const tn = e.tagName.toLowerCase()
    return `export const ${tn} = Render('${tn}')`
  }
  const tags = $$(selector).map((a) => a.textContent.replace(/[<|>]/g, ``))
  const elements = tags.sort().map((t) => document.createElement(t))
  return elements.map(stringify).join(`\n`)
})()

 * Minor fixups might be required, ie. missing h2 - h6
 *
 * - GENERATED CODE -
 */

export const a = Render("a")
export const abbr = Render("abbr")
export const acronym = Render("acronym")
export const address = Render("address")
export const applet = Render("applet")
export const area = Render("area")
export const article = Render("article")
export const aside = Render("aside")
export const audio = Render("audio")
export const b = Render("b")
export const base = Render("base")
export const basefont = Render("basefont")
export const bdi = Render("bdi")
export const bdo = Render("bdo")
export const bgsound = Render("bgsound")
export const big = Render("big")
export const blink = Render("blink")
export const blockquote = Render("blockquote")
export const body = Render("body")
export const br = Render("br")
export const button = Render("button")
export const canvas = Render("canvas")
export const caption = Render("caption")
export const center = Render("center")
export const cite = Render("cite")
export const code = Render("code")
export const col = Render("col")
export const colgroup = Render("colgroup")
export const command = Render("command")
export const content = Render("content")
export const data = Render("data")
export const datalist = Render("datalist")
export const dd = Render("dd")
export const del = Render("del")
export const details = Render("details")
export const dfn = Render("dfn")
export const dialog = Render("dialog")
export const dir = Render("dir")
export const div = Render("div")
export const dl = Render("dl")
export const dt = Render("dt")
export const element = Render("element")
export const em = Render("em")
export const embed = Render("embed")
export const fieldset = Render("fieldset")
export const figcaption = Render("figcaption")
export const figure = Render("figure")
export const font = Render("font")
export const footer = Render("footer")
export const form = Render("form")
export const frame = Render("frame")
export const frameset = Render("frameset")
export const h1 = Render("h1")
export const h2 = Render("h2")
export const h3 = Render("h3")
export const h4 = Render("h4")
export const h5 = Render("h5")
export const h6 = Render("h6")
export const head = Render("head")
export const header = Render("header")
export const hgroup = Render("hgroup")
export const hr = Render("hr")
export const html = Render("html")
export const i = Render("i")
export const iframe = Render("iframe")
export const image = Render("image")
export const img = Render("img")
export const input = Render("input")
export const ins = Render("ins")
export const isindex = Render("isindex")
export const kbd = Render("kbd")
export const keygen = Render("keygen")
export const label = Render("label")
export const legend = Render("legend")
export const li = Render("li")
export const link = Render("link")
export const listing = Render("listing")
export const main = Render("main")
export const map = Render("map")
export const mark = Render("mark")
export const marquee = Render("marquee")
export const menu = Render("menu")
export const menuitem = Render("menuitem")
export const meta = Render("meta")
export const meter = Render("meter")
export const multicol = Render("multicol")
export const nav = Render("nav")
export const nextid = Render("nextid")
export const nobr = Render("nobr")
export const noembed = Render("noembed")
export const noframes = Render("noframes")
export const noscript = Render("noscript")
export const object = Render("object")
export const ol = Render("ol")
export const optgroup = Render("optgroup")
export const option = Render("option")
export const output = Render("output")
export const p = Render("p")
export const param = Render("param")
export const picture = Render("picture")
export const plaintext = Render("plaintext")
export const pre = Render("pre")
export const progress = Render("progress")
export const q = Render("q")
export const rb = Render("rb")
export const rp = Render("rp")
export const rt = Render("rt")
export const rtc = Render("rtc")
export const ruby = Render("ruby")
export const s = Render("s")
export const samp = Render("samp")
export const script = Render("script")
export const section = Render("section")
export const select = Render("select")
export const shadow = Render("shadow")
export const slot = Render("slot")
export const small = Render("small")
export const source = Render("source")
export const spacer = Render("spacer")
export const span = Render("span")
export const strike = Render("strike")
export const strong = Render("strong")
export const style = Render("style")
export const sub = Render("sub")
export const summary = Render("summary")
export const sup = Render("sup")
export const table = Render("table")
export const tbody = Render("tbody")
export const td = Render("td")
export const template = Render("template")
export const textarea = Render("textarea")
export const tfoot = Render("tfoot")
export const th = Render("th")
export const thead = Render("thead")
export const time = Render("time")
export const title = Render("title")
export const tr = Render("tr")
export const track = Render("track")
export const tt = Render("tt")
export const u = Render("u")
export const ul = Render("ul")
export const video = Render("video")
export const wbr = Render("wbr")
export const xmp = Render("xmp")
